# Generated by Django 4.1.7 on 2025-03-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ф.И.О.')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsapp.ad')),
            ],
        ),
    ]
