services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=crm_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5433:5432"
    volumes:
      - ./databases/:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d crm_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser --no-input || true &&
             gunicorn DjangoCRM.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
