# Generated by Django 4.1.7 on 2025-03-07 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractsapp', '0003_alter_contract_document'),
        ('leadsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contractsapp.contract')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leadsapp.lead')),
            ],
        ),
    ]
