# Generated by Django 4.1.7 on 2025-03-07 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadsapp", "0001_initial"),
        ("contractsapp", "0003_alter_contract_document"),
        ("customersapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="contract",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="contractsapp.contract",
                verbose_name="Контракт",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="lead",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="leadsapp.lead",
                verbose_name="Потенциальный клиент",
            ),
        ),
    ]
