"""
Django settings for DjangoCRM project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
import sys
from datetime import datetime
from os import getenv
from pathlib import Path

from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-_a_d=bdd^32q@!zb_pwix*jr9otof+985c*$c36vmb$ihr8(&4",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = getenv("DJANGO_DEBUG", "0") == "1"
TESTING = "test" in sys.argv

ALLOWED_HOSTS = [
                    "127.0.0.1",
                    "0.0.0.0",
                    "localhost",
                ] + getenv(
    "DJANGO_ALLOWED_HOSTS", ""
).split(",")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "myauth.apps.MyauthConfig",
    "productapp.apps.ProductappConfig",
    "adsapp.apps.AdsappConfig",
    "leadsapp.apps.LeadsappConfig",
    "contractsapp.apps.ContractsappConfig",
    "customersapp.apps.CustomersappConfig",
    "statisticsapp.apps.StatisticsappConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "DjangoCRM.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "DjangoCRM.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
if TESTING:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "crm_db",
            "USER": "admin",
            "PASSWORD": "admin",
            "HOST": "db",
            "PORT": "5432",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_ROOT = BASE_DIR / "uploads"  # строим путь до папки с файлами
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = reverse_lazy("myauth:about_me")  # куда перенаправить после входа

LOGIN_URL = reverse_lazy("myauth:login")  # куда перенаправлять для входа

LOGLEVEL = getenv("LOGLEVEL", "INFO")  # по умолчанию INFO

# Настройка логов
LOGDIR = BASE_DIR / "logs"
LOGDIR.mkdir(exist_ok=True)
LOGFILE_NAME = LOGDIR / f"django_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.log"
LOGFILE_SIZE = 1 * 1024 * 1024  # 1мБ
LOGFILE_COUNT = 3

# Настройка логирования
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,  # параметр указывается для того, чтобы не отключать существующие логи
    "formatters": {  # укаазание формата вывода
        "verbose": {  # подробные логи
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "logfile": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": LOGFILE_NAME,  # имя файла
            "backupCount": LOGFILE_COUNT,  # сколько файлов хранить
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": [
            "console",
            "logfile",
        ],
        "level": "INFO",
    },
}
