# Generated by Django 4.1.7 on 2025-03-06 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("promotion_channel", models.CharField(max_length=100)),
                (
                    "advertising_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productapp.product",
                    ),
                ),
            ],
        ),
    ]
