# Generated by Django 4.1.7 on 2025-03-08 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productapp", "0001_initial"),
        ("adsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="advertising_budget",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Бюджет на рекламу",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Название рекламной компании"
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="productapp.product",
                verbose_name="Услуга",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="promotion_channel",
            field=models.CharField(max_length=100, verbose_name="Канал продвижения"),
        ),
    ]
