# Generated by Django 4.1.7 on 2025-03-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название контракта"),
                ),
                (
                    "document",
                    models.FileField(
                        null=True,
                        upload_to="documents/contract/",
                        verbose_name="Файл с документом",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата заключения"),
                ),
                ("end_date", models.DateField(verbose_name="Период действия")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="Сумма"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productapp.product",
                        verbose_name="Предоставляемая услуга",
                    ),
                ),
            ],
        ),
    ]
